[workspace]

members = [
    "spikes/update",
    "spikes/clickhouse-ingest"
    ]

[package]
name = "wikidumptools"
version = "0.0.1"
authors = ["Count Count <countvoncount123456@gmail.com>"]
edition = "2018"

[dependencies]
quick-xml = "0.22.0"
regex = "1"
clap = "3.0.0-beta.2"
memchr = "2.3.3"
termcolor = "1.1"
rayon = "1.3.1"
atty = "0.2.14"
thiserror = "1.0.20"
anyhow = "1.0"
reqwest = "0.11"
tokio = { version = "1.3", features = ["rt", "macros", "time", "signal"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha-1 = "0.9.1"
lazy_static = "1.4"

[dependencies.snmalloc-rs]
version = "0.2.24"
features = [] # stats, debug, ...

[dev-dependencies]
bzip2 = "0.4.1"
slice = "0.0.4"

[profile.release]
#debug = "yes" # for profiling

# minimize size of binaries
#lto = "yes"
#codegen-units = 1
#opt-level = 'z' # possible s or 3 instead (benchmark!)
#panic = 'abort'
