[package]
name = "wikidumpgrep"
version = "0.1.0"
authors = ["Count Count"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.18.1"
regex = "1"
clap = "2.33.1"

[dependencies.snmalloc-rs]
version = "0.2"
features = [] # stats, debug, ...

[profile.release]
lto = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false